config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users,
    path: '',
    path_names: {
      sign_up: '',
      sign_in: 'login',
      sign_out: 'logout',
      registration: "signup",
    },
    controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions",
      confirmations: "users/confirmations"
    }
  resources :users, only: [:index, :show] do
    member do
      get :following, :followers
    end
  end
  resources :posts, only: [:index, :new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :stampbooks do
    collection do
      get :owners
    end
  end
  resources :stamps do
    collection do
      get :owners
      get :search
    end
  end
  resources :maps, only: :index
  
  resources :likes, only: [:create, :destroy]
end

app/models/stampbook.rb
class Stampbook < ApplicationRecord
  belongs_to :user
  has_many :stamps, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  mount_uploader :cover, CoverUploader
  validates :user_id, presence: true
  validates :name, presence: true
end

app/controllers/stampbooks_controller.rb
class StampbooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: :destroy

  def index
    @stampbooks = Stampbook.page(params[:page]).per(15)

  end

  def show
    @user = User.find(params[:id])
    @stampbook = Stampbook.find(params[:id])
    @stampbooks = @stampbook.user.stampbooks.page(params[:page])
  end

  def new
    @stampbook = Stampbook.new
  end

  def create
    @stampbook = current_user.stampbooks.build(stampbook_params)
    if @stampbook.save
      flash[:success] = "御朱印帳が登録されました！"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @stampbook = current_user.stampbooks.find_by(id: params[:id])
  end

  def update
    @stampbook = current_user.stampbooks.find_by(id: params[:id])
    if @stampbook.update_attributes(stampbook_params)
      flash[:notice] = "御朱印帳の編集に成功しました"
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @stampbook.destroy
    flash[:notice] = "御朱印帳を削除しました"
    redirect_to request.referrer || root_url
  end

  def owners
    @user = User.find(params[:id])
    @stampbook = @user.stampbooks.first
    @stampbooks = @user.stampbooks.page(params[:page])
    render 'show'
  end

  private

  def stampbook_params
    params.require(:stampbook).permit(:name, :given_date, :cover, :remove_cover, :cover_cache, :remarks, :distinction)
  end

  def correct_user
    @stampbook = current_user.stampbooks.find_by(id: params[:id])
    redirect_to root_url if @stampbook.nil?
  end
end

app/helpers/stampbooks_helper.rb
module StampbooksHelper
end

app/views/stampbooks/_form.html.erb
<%= form_with model: @stampbook, local: true do |f| %>
<%= render 'shared/error_messages', object: f.object %>

<div class="form-group">
  <%= f.label :name, "御朱印帳名" %>
  <%= f.text_field :name, autofocus: false, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :given_date, "取得日" %>
  <%= f.date_field :given_date, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :cover, "御朱印帳の画像" %>
  <div id="img_photo" onClick="$('#file').click()">
    <% if @stampbook.cover.present? %>
    <%= image_tag(@stampbook.cover.to_s, size: "400x300") %>
    <% else %>
    <i class="fas fa-image"></i><i class="fas fa-file-upload add"></i>
    <% end %>
  </div>
  <%= f.file_field :cover, class: 'form-control-file', style: "display:none;", id: "file" %>
  <%= f.hidden_field :cover_cache %>

</div>

<div class="form-check">
  <p>
    <label>
      <%= f.check_box :remove_cover, class: 'form-check-input' %> 画像を削除する
    </label>
  </p>
</div>

<div class="form-check form-check-inline">
  <%= f.radio_button(:distinction, "神社", class: 'form-check-input') %>
  <%= f.label(:distinction, "神社", value: "神社", class: 'form-check-label') %>
  <%= f.radio_button(:distinction, "寺院", class: 'form-check-input') %>
  <%= f.label(:distinction, "寺院", value: "寺院", class: 'form-check-label') %>
</div>

<div class="form-group">
  <%= f.label :remarks, "説明文" %>
  <%= f.text_area :remarks, autofocus: false, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.submit "送信", class: "btn btn-primary btn-block btn-lg" %>
</div>
<% end %>

app/views/stampbooks/_stampbook.html.erb
<div class="row d-flex">
  <% stampbooks.each do |stampbook| %>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-header">
        <%= link_to stampbook.name, stampbook %>
      </div>
      <div class="stampbook text-center">
        <%= image_tag stampbook.cover.to_s, class: "card-img-top" %>
      </div>
    </div>
  </div>
  <% end %>
  <%= paginate stampbooks %>
</div>

app/views/stampbooks/edit.html.erb
<div class="row">
  <div class="col-lg-4 col-md-6 ml-auto mr-auto">
    <h1 class="text-center">御朱印帳の編集</h1>
    <hr>
    <%= render 'stampbooks/form'%>
  </div>
</div>

app/views/stampbooks/index.html.erb
<% provide :title, '御朱印帳一覧' %>
<div class="container">
  <h2><i class="fas fa-book stampbook-color"></i> みんなの御朱印帳</h2>
  <ul class="stampbooks">
    <% @stampbooks.each do |stampbook| %>
    <li>
      <span class="stampbook-name"><%= link_to stampbook.name, stampbook %></span><br />
      <%= image_tag stampbook.cover.to_s, class: "stampbook", size:  "300x200" %>
      <span class="stampbook-name"><i class="fas fa-book stampbook-color"></i> <%= link_to stampbook.name, stampbook %></span>
      <span>取得日<%= stampbook.given_date %></span>
      <span>メモ<%= stampbook.remarks %></span>
      <span>収録御朱印数<%= stampbook.stamps.count %></span>
    </li>
    <% end %>
  </ul>
  <%= paginate @stampbooks %>
</div>

app/views/stampbooks/new.html.erb
<div class="row">
  <div class="col-lg-4 col-md-6 ml-auto mr-auto">
    <h1 class="text-center">御朱印帳の登録</h1>
    <hr>
    <%= render 'stampbooks/form'%>
  </div>
</div>

app/views/stampbooks/show.html.erb
<div class="container">
  <% unless @stampbook.nil? %>
  <div class="row">
    <div class="col-xs-12 col-md-6">
      <div class="show-title stampbook-color">
        <% if current_user?(@user) %>
        <h2 class="wf-sawarabimincho"><i class="fas fa-book"></i> My御朱印帳</h2>
        <% else %>
        <h2><i class="fas fa-book"></i><%= @user.name %>の御朱印帳</h2>
        <% end%>
      </div>
      <div class="row d-flex justify-content-center">
        <div class="card">
          <div class="stampbook text-center"><%= image_tag @stampbook.cover.to_s, class: "card-img-top" %>
          </div>
          <div class="card-body">
            <div class="card-title">
              <span class="wf-sawarabimincho stampbook-name"><%= @stampbook.name %></span>
            </div>
            <table>
              <tr>
                <th>神社/寺院</th>
                <td><%= @stampbook.distinction %></td>
              </tr>
              <tr>
                <th>取得日</th>
                <td><%= @stampbook.given_date %></td>
              </tr>
              <tr>
                <th>御朱印の数</th>
                <td><%= @stampbook.stamps.count %></td>
              </tr>
            </table>
            <p class="card-text"><%= @stampbook.remarks %></p>
            <span><%= link_to "編集", edit_stampbook_path(@stampbook) %></span>
            <span><%= link_to "削除", @stampbook, method: :delete, data: { confirm: "登録されている御朱印も削除されます。本当に削除しますか？" } %></span>
          </div>
        </div>
      </div>
    </div>


    <div class="col-xs-12 col-md-6">
      <div class="show-title">
        <h3><%= @stampbook.user.name %> さんの御朱印帳一覧</h3>
      </div>
      <%= render partial: 'stampbook', locals: { stampbooks: @stampbooks } %>
    </div>
    <% else %>
    <p><%= @user.name %>さんはまだ御朱印帳を登録されていません</p>
    <% end %>
  </div>
</div>