config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users,
    path: '',
    path_names: {
      sign_up: '',
      sign_in: 'login',
      sign_out: 'logout',
      registration: "signup",
    },
    controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions",
      confirmations: "users/confirmations"
    }
  resources :users, only: [:index, :show] do
    member do
      get :following, :followers
    end
  end
  resources :posts, only: [:index, :new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :stampbooks do
    collection do
      get :owners
    end
  end
  resources :stamps do
    collection do
      get :owners
      get :search
    end
  end
  resources :maps, only: :index
  
  resources :likes, only: [:create, :destroy]
end

app/models/stamp.rb
class Stamp < ApplicationRecord
  belongs_to :stampbook
  has_one :user, through: :stampbook
  default_scope -> { order(created_at: :desc) }
  mount_uploader :photo, PhotoUploader
  validates :name, presence: true
  validates :photo, presence: true
  validates :stampbook_id, presence: true

  scope :search, -> (search_params) do
    return if search_params.blank?

    name_like(search_params[:name])
      .distinction_is(search_params[:distinction])
      .given_date_from(search_params[:given_date_from])
      .given_date_to(search_params[:given_date_to])
      .stampbook_id_is(search_params[:stampbook_id])
  end
  scope :name_like, -> (name) { where('name LIKE ?', "%#{name}%") if name.present? }
  scope :distinction_is, -> (distinction) { where(distinction: distinction) if distinction.present? }
  scope :given_date_from, -> (from) { where('? <= given_date', from) if from.present? }
  scope :given_date_to, -> (to) { where('given_date <= ?', to) if to.present? }
  scope :stampbook_id_is, -> (stampbook_id) { where(stampbook_id: stampbook_id) if stampbook_id.present? }
end

app/controllers/stamps_controller.rb
class StampsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user, only: :destroy
  before_action :set_select_collections, only: [:new, :create, :edit, :update]

  def index
    @stamps = Stamp.page(params[:page]).per(15)

  end
  
  def show
    @stamp = Stamp.find(params[:id])
    @user = @stamp.user
    @stamps = @stamp.user.stamps.page(params[:page])
    @stampbooks = @user.stampbooks.page(params[:page])
  end

  def new
    @stamp = Stamp.new
  end

  def create
    @stamp = Stamp.new(stamp_params)
    if @stamp.save
      flash[:success] = "御朱印が登録されました！"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @stamp = Stamp.find(params[:id])
  end

  def update
    @stamp = current_user.stamps.find_by(id: params[:id])
    if @stamp.update_attributes(stamp_params)
      flash[:notice] = "御朱印の編集に成功しました"
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @stamp.destroy
    flash[:notice] = "御朱印を削除しました"
    redirect_to request.referrer || root_url
  end

  def owners
    @user = User.find(params[:id])
    @stamp = @user.stamps.first
    @stamps = @user.stamps.page(params[:page])
    @stampbooks = @user.stampbooks
    render 'show'
  end

  def search
    @search_params = stamp_search_params
    @stamps = Stamp.search(@search_params).includes(:stampbook)
  end

  private

  def stamp_params
    params.require(:stamp).permit(:name, :given_date, :photo, :remove_photo, :photo_cache, :remarks, :distinction, :stampbook_id)
  end

  def stamp_search_params
    params.fetch(:search, {}).permit(:name, :distinction, :given_date_from, :given_date_to, :stampbook_id)
  end

  def correct_user
    @stamp = current_user.stamps.find_by(id: params[:id])
    redirect_to root_url if @pstamp.nil?
  end

  def set_select_collections
    @stampbooks = current_user.stampbooks
  end
end

app/helpers/stamps_helper.rb
module StampsHelper
end

app/views/stamps/_form.html.erb
<%= form_with model: @stamp, local: true do |f| %>
<%= render 'shared/error_messages', object: f.object %>

<div class="form-group">
  <%= f.label :stampbook_id, "登録する御朱印帳" %>
  <%= f.collection_select(:stampbook_id, @stampbooks, :id, :name, {prompt: "御朱印帳を選んでください"}, {class: 'form-control'}) %>
</div>

<div class="form-group">
  <%= f.label :name, "御朱印名" %>
  <%= f.text_field :name, autofocus: false, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :given_date, "取得日" %>
  <%= f.date_field :given_date, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :photo, "御朱印の画像" %>
  <div id="img_photo" onClick="$('#file').click()">
    <% if @stamp.photo.present? %>
    <%= image_tag(@stamp.photo.to_s, auto_orient: true) %>
    <% else %>
    <i class="fas fa-image"></i><i class="fas fa-file-upload add"></i>
    <% end %>
  </div>
  <%= f.file_field :photo, class: 'form-control-file', style: "display:none", id: "file" %>
  <%= f.hidden_field :photo_cache %>
</div>

<div class="form-check">
  <p>
    <label>
      <%= f.check_box :remove_photo, class: 'form-check-input' %> 画像を削除する
    </label>
  </p>
</div>

<div class="form-check form-check-inline">
  <%= f.radio_button(:distinction, "神社", class: 'form-check-input') %>
  <%= f.label(:distinction, "神社", value: "神社", class: 'form-check-label') %>
  <%= f.radio_button(:distinction, "寺院", class: 'form-check-input') %>
  <%= f.label(:distinction, "寺院", value: "寺院", class: 'form-check-label') %>
</div>

<div class="form-group">
  <%= f.label :remarks, "説明文" %>
  <%= f.text_area :remarks, autofocus: false, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.submit "送信", class: "btn btn-primary btn-block btn-lg" %>
</div>
<% end %>

app/views/stamps/_stamp.html.erb
<div class="row d-flex justify-content-center">
  <% stamps.each do |stamp| %>
  <div class="stamps col-sm-6">
    <div class="card w-75">
      <div class="card-header">
        <%= link_to stamp.name, stamp %>
      </div>
      <div class="stamp text-center">
        <%= image_tag stamp.photo.to_s, class: "card-img-top" %>
      </div>
    </div>
  </div>
  <% end %>
  <%= paginate stamps %>
</div>

app/views/stamps/edit.html.erb
<div class="row">
  <div class="col-lg-4 col-md-6 ml-auto mr-auto">
    <h1 class="text-center wf-sawarabimincho">御朱印の編集</h1>
    <hr>
    <%= render 'stamps/form'%>
  </div>
</div>

app/views/stamps/index.html.erb
<% provide :title, '御朱印一覧' %>
<div class="container">
  <h2><i class="fas fa-stamp stamp-color"></i> みんなの御朱印</h2>
  <%= render partial: 'stamp',  locals: { stamps: @stamps } %>
</div>

app/views/stamps/new.html.erb
<div class="row">
  <div class="col-lg-4 col-md-6 ml-auto mr-auto">
    <h1 class="text-center wf-sawarabimincho">御朱印の登録</h1>
    <hr>
    <%= render 'stamps/form'%>
  </div>
</div>

app/views/stamps/search.html.erb
<div class="row">
  <div class="col-lg-4 col-md-6 ml-auto mr-auto">
    <h2 class="text-center wf-sawarabimincho">御朱印検索</h2>
    <hr>
    <%= form_with scope: :search, url: search_stamps_path, method: :get, local: true do |f| %>
    <div class="form-group">
      <%= f.label :name, "御朱印名" %>
      <%= f.text_field :name, value: @search_params[:name], class: 'form-control' %>
    </div>
    <div class="form-check form-check-inline">
      <%= f.radio_button(:distinction, "神社", class: 'form-check-input') %>
      <%= f.label(:distinction, "神社", value: "神社", class: 'form-check-label') %>
      <%= f.radio_button(:distinction, "寺院", class: 'form-check-input') %>
      <%= f.label(:distinction, "寺院", value: "寺院", class: 'form-check-label') %>
    </div>
    <div class="form-group">
      <%= f.label :given_date, "登録日" %>
      <%= f.date_field :given_date_from, value: @search_params[:given_date_from], class: 'form-control' %> ~ <%= f.date_field :given_date_to, value: @search_params[:given_date_to], class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :stampbook_id, "御朱印帳名" %>
      <%= f.text_field :stampbook_id, value: @search_params[:stampbook_id], class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.submit "検索", class: "btn btn-primary btn-block btn-lg" %>
    </div>
    <% end %>
    <div class="search-result">
      <h3><i class="fas fa-search"></i>検索結果</h3>
      <table>
        <thead>
          <tr>
            <th>御朱印名</th>
            <th>御朱印帳名</th>
            <th>ユーザー名</th>
            <th>神社/寺院</th>
            <th>登録日</th>
          </tr>
        </thead>

        <tbody>
          <% @stamps.each do |stamp| %>
          <tr>
            <td><%= link_to stamp.name, stamp %></td>
            <td><%= stamp.stampbook.name %></td>
            <td><%= stamp.user.name %></td>
            <td><%= stamp.distinction %></td>
            <td><%= stamp.given_date %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/stamps/show.html.erb
<div class="container">
  <% unless @stamp.nil? %>
  <div class="row">
    <div class="col-xs-12 col-md-6">
      <div class="show-title">
        <% if current_user?(@user) %>
        <h2 class="wf-sawarabimincho"><i class="fas fa-stamp"></i> My御朱印</h2>
        <% else %>
        <h2><i class="fas fa-stamp"></i><%= @user.name %>の御朱印</h2>
        <% end%>
      </div>
      <div class="row d-flex justify-content-center">
        <div class="card w-75">
          <div class="stamp text-center"><%= image_tag @stamp.photo.to_s, class: "card-img"%>
          </div>
          <div class="card-body">
            <div class="card-title">
              <span class="wf-sawarabimincho stamp-name"><%= @stamp.name %></span>
            </div>
            <table>
              <tr>
                <th>神社/寺院</th>
                <td><%= @stamp.distinction %></td>
              </tr>
              <tr>
                <th>取得日</th>
                <td><%= @stamp.given_date %></td>
              </tr>
              <tr>
                <th>御朱印帳</th>
                <td><%= @stamp.stampbook.name %></td>
              </tr>
            </table>
            <p class="card-text"><%= @stamp.remarks %></p>
            <span><%= link_to "編集", edit_stamp_path(@stamp) %></span>
            <span><%= link_to "削除", @stamp, method: :delete, data: { confirm: "本当に削除しますか？" } %></span>
          </div>
        </div>
      </div>
    </div>

    <div class="col-xs-12 col-md-6">
      <div class="show-title">
        <h3><%= @stamp.user.name %> さんの御朱印一覧</h3>
      </div>
      <%= render partial: 'stamp', locals: { stamps: @stamps } %>
    </div>

    <% else %>
    <p><%= @user.name %>さんはまだ御朱印を登録されていません</p>
    <% end %>
  </div>
</div>