config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users,
    path: '',
    path_names: {
      sign_up: '',
      sign_in: 'login',
      sign_out: 'logout',
      registration: "signup",
    },
    controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions",
      confirmations: "users/confirmations"
    }
  resources :users, only: [:index, :show] do
    member do
      get :following, :followers
    end
  end
  resources :posts, only: [:index, :new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :stampbooks do
    collection do
      get :owners
    end
  end
  resources :stamps do
    collection do
      get :owners
      get :search
    end
  end
  resources :maps, only: :index
  
  resources :likes, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post, counter_cache: :likes_count
  belongs_to :user
  validates :user_id, presence: true
  validates :post_id, presence: true
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }

  def like(user)
    likes.create(user_id: user.id)
  end

  def unlike(user)
    likes.find_by(user_id: user.id).destroy
  end

  def like?(user)
   like_users.include?(user)
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/stamp.rb
class Stamp < ApplicationRecord
  belongs_to :stampbook
  has_one :user, through: :stampbook
  default_scope -> { order(created_at: :desc) }
  mount_uploader :photo, PhotoUploader
  validates :name, presence: true
  validates :photo, presence: true
  validates :stampbook_id, presence: true

  scope :search, -> (search_params) do
    return if search_params.blank?

    name_like(search_params[:name])
      .distinction_is(search_params[:distinction])
      .given_date_from(search_params[:given_date_from])
      .given_date_to(search_params[:given_date_to])
      .stampbook_id_is(search_params[:stampbook_id])
  end
  scope :name_like, -> (name) { where('name LIKE ?', "%#{name}%") if name.present? }
  scope :distinction_is, -> (distinction) { where(distinction: distinction) if distinction.present? }
  scope :given_date_from, -> (from) { where('? <= given_date', from) if from.present? }
  scope :given_date_to, -> (to) { where('given_date <= ?', to) if to.present? }
  scope :stampbook_id_is, -> (stampbook_id) { where(stampbook_id: stampbook_id) if stampbook_id.present? }
end

app/models/stampbook.rb
class Stampbook < ApplicationRecord
  belongs_to :user
  has_many :stamps, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  mount_uploader :cover, CoverUploader
  validates :user_id, presence: true
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :stampbooks, dependent: :destroy
  has_many :stamps, through: :stampbooks
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  has_many :active_relationships,
        class_name: 'Relationship',
       foreign_key: :follower_id,
         dependent: :destroy
  has_many :passive_relationships,
        class_name: 'Relationship',
       foreign_key: :followed_id,
         dependent: :destroy
  # @user.active_relationships.map(&:followed)
  # @user.following
  has_many :following,
    through: 'active_relationships',
     source: 'followed'
  has_many :followers,
    through: 'passive_relationships',
     source: 'follower'

  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :name, presence: true

  def feed
    following_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
    Post.where("user_id IN (#{following_ids}) OR user_id = :user_id",user_id: self.id)
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  # def already_liked?(post)
  #   self.likes.exists?(post_id: post.id)
  # end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      @post = current_user.posts.build
      @feed_items = current_user.feed.page(params[:page])
      @stampbooks = current_user.stampbooks.page(params[:page])
      @stamps = current_user.stamps.page(params[:page])
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    return if @post.like?(current_user)

    @post.like(current_user)
    @post.reload
    respond_to do |format|
      format.html { redirect_to request.referrer || root_url }
      format.js
    end
  end

  def destroy
    @post = Like.find(params[:id]).post
    return unless @post.like?(current_user)

    @post.unlike(current_user)
    @post.reload
    respond_to do |format|
      format.html { redirect_to request.referrer || root_url}
      format.js
    end
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: :destroy

  def index
    @posts = Post.page(params[:page]).per(10)
    @feed_items = current_user.feed.page(params[:page])
  end

  def new
    @post = current_user.posts.build 
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "記事が投稿されました"
      redirect_to current_user
    else
      @feed_items = []
      render 'users/sessions/new'
    end
  end

  def destroy
    @post.destroy
    flash[:alert] = "記事を削除しました"
    redirect_to request.referrer || current_user
  end

  private

  def post_params
    params.require(:post).permit(:content, :picture, :remove_picture, :picture_cache)
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_url if @post.nil?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :following, :followers]

  def index
    @users = User.page(params[:page]).per(15)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(10)
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.page(params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.page(params[:page])
    render 'show_follow'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user?(user)
    user == curennt_user
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/stampbooks_helper.rb
module StampbooksHelper
end

app/helpers/stamps_helper.rb
module StampsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
 end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
    <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
        <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
<ol class="posts">
    <%= render @feed_items %>
</ol>
<%= paginate @feed_items %>
<% end %>

app/views/shared/_owners.html.erb
<% user ||= current_user %>
<div class="owners">
  <a href="<%= owners_stampbooks_path(id: user.id) %>">
    <strong class="owners">
      <%= user.stampbooks.count %>
    </strong>
    <i class="fas fa-book fa-2x"></i>
  </a>
  <a href="<%= owners_stamps_path(id: user.id) %>">
    <strong class="owners">
      <%= user.stamps.count %>
    </strong>
    <i class="fas fa-stamp fa-2x"></i>
  </a>
</div>

app/views/shared/_post_form.html.erb
<%= form_with model: @post do |f| %>
<%= render 'shared/error_messages', object:f.object %>
<div class="form-group">
  <%= f.text_area :content, size: "50x5", class: "form-controll", placeholder: "投稿記事を書いてください" %>
</div>
<div class="picture">
  <%= f.label "画像添付時は下記をタップ" %>
  <div id="img_photo" onClick="$('#file').click()">
    <i class="fas fa-image"></i><i class="fas fa-file-upload add"></i>
  </div>
  <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', class: 'form-control-file', style: "display:none;", id: "file" %>
  <%= f.hidden_field :picture_cache %>
</div>
<%= f.submit "投稿する", class: "btn btn-primary"%>

<% end %>

app/views/shared/_stats.html.erb
<% user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(user) %>">
    <strong id="following" class="stat">
      <%= user.following.count %>
    </strong>
    フォロー
  </a>
  <a href="<%= followers_user_path(user) %>">
    <strong id="followers" class="stat">
      <%= user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= image_tag current_user.avatar.to_s, class: "circle-avatar mb-2 mx-auto", size: "100x100", alt: "アバター" %>
<h2><%= current_user.name %></h2>