config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users,
    path: '',
    path_names: {
      sign_up: '',
      sign_in: 'login',
      sign_out: 'logout',
      registration: "signup",
    },
    controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions",
      confirmations: "users/confirmations"
    }
  resources :users, only: [:index, :show] do
    member do
      get :following, :followers
    end
  end
  resources :posts, only: [:index, :new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :stampbooks do
    collection do
      get :owners
    end
  end
  resources :stamps do
    collection do
      get :owners
      get :search
    end
  end
  resources :maps, only: :index
  
  resources :likes, only: [:create, :destroy]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      @post = current_user.posts.build
      @feed_items = current_user.feed.page(params[:page])
      @stampbooks = current_user.stampbooks.page(params[:page])
      @stamps = current_user.stamps.page(params[:page])
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>
<div class="row d-flex justify-content-center">
  <div class="col-sm-12 aside">
    <div class="user-info">
      <%= render 'shared/user_info' %>
    </div>
    <div class="stats">
      <%= render 'shared/stats', user: @user %>
    </div>
    <div class="owners">
      <%= render 'shared/owners' %>
    </div>
  </div>

  <div class="col-sm-4 col-md-4 top-boxes">
    <div class="top-content">
      <div class="top-icon">
        <%= link_to owners_stampbooks_path(id: current_user.id) do %>
        <i class="fas fa-book fa-5x fa-fw"></i>
        <% end %>
      </div>
      <%= link_to "My御朱印帳", owners_stampbooks_path(id: current_user.id) %>
    </div>
  </div>

  <div class="col-sm-4 col-md-4 top-boxes">
    <div class="top-content">
      <div class="top-icon">
        <%= link_to owners_stamps_path(id: current_user.id) do %>
        <i class="fas fa-stamp fa-5x fa-fw"></i>
        <% end %>
      </div>
      <%= link_to "My御朱印", owners_stamps_path(id: current_user.id) %>
    </div>
  </div>

  <div class="col-sm-4 col-md-4 top-boxes">
    <div class="top-content">
      <div class="top-icon">
        <%= link_to new_stampbook_path do %>
        <i class="fas fa-image fa-5x fa-fw"></i>
        <% end %>
      </div>
      <%= link_to "御朱印帳を登録する", new_stampbook_path %>
    </div>
  </div>

  <div class="col-sm-4 col-md-4 top-boxes">
    <div class="top-content">
      <div class="top-icon">
        <%= link_to new_stamp_path do %>
        <i class="fas fa-images fa-5x fa-fw"></i>
        <% end %>
      </div>
      <%= link_to "御朱印を登録する", new_stamp_path %>
    </div>
  </div>

  <div class="col-sm-4 col-md-4 top-boxes">
    <div class="top-content">
      <div class="top-icon">
        <%= link_to current_user do %>
        <i class="fas fa-address-card fa-5x fa-fw"></i>
        <% end %>
      </div>
      <%= link_to "Myアカウント", current_user %>
    </div>
  </div>

  <div class="col-sm-4 col-md-4 top-boxes">
    <div class="top-content">
      <div class="top-icon">
        <%= link_to new_post_path do %>
        <i class="far fa-comment-alt fa-5x fa-fw"></i>
        <% end %>
      </div>
      <%= link_to "投稿する", new_post_path %>
    </div>
  </div>

  <div class="col-sm-4 col-md-4 top-boxes">
    <div class="top-content">
      <div class="top-icon">
        <%= link_to maps_path do %>
        <i class="fas fa-torii-gate fa-5x fa-fw"></i>
        <% end %>
      </div>
      <%= link_to "近くの神社・寺院", maps_path %>
    </div>
  </div>

  <div class="col-sm-4 col-md-4 top-boxes">
    <div class="top-content">
      <div class="top-icon">
        <%= link_to search_stamps_path do %>
        <i class="fas fa-search fa-5x fa-fw"></i>
        <% end %>
      </div>
      <%= link_to "御朱印検索", search_stamps_path %>
    </div>
  </div>

</div>


<% else %>

<!-- ======= Hello Section ======= -->
<section id="hello">
  <div class="hello-container">
    <h1>ようこそ御朱印管理アプリへ</h1>
    <h2>
      御朱印を思い出と共に記録しましょう。</h2>
    <a href="#about" class="btn-get-started scrollto">機能紹介</a>
    <%= link_to "新規登録", new_user_registration_path, class: "btn-get-started scrollto" %>
  </div>
</section>
<!-- #hero -->

<main id="main">

  <!-- ======= About Us Section ======= -->

  <section id="about" class="about">
    <div class="container">

      <div class="section-title">
        <h2>このアプリで出来ること</h2>
      </div>

      <div class="row">

        <div class="col-lg-6 order-1 order-lg-2">
          <%= image_tag("about-gosyuin.jpg", class: "img-fluid", alt: "御朱印帳", ) %>
        </div>

        <div class="col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1">
          <h3>御朱印は御朱印帳ごとに登録出来るので、どこにあるかがすぐにわかります。</h3>
          <p class="font-italic">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
            dolore
            magna aliqua.
          </p>
          <ul>
            <li><i class="icofont-check-circled"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat.</li>
            <li><i class="icofont-check-circled"></i> Duis aute irure dolor in reprehenderit in voluptate velit.</li>
            <li><i class="icofont-check-circled"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis
              aute irure dolor in reprehenderit in voluptate trideta storacalaperda mastiro dolore eu fugiat nulla
              pariatur.</li>
          </ul>
          <p>
            Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
            voluptate
            velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
            culpa qui officia deserunt mollit anim id est laborum
          </p>
        </div>
      </div>
    </div>
</main>
<% end %>